services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
#      - /app/node_modules
#      - /app/dist
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
