services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
  db:
    image: mysql:8.4.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: honox_example2
